### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by sandrinecharles** [bgoussen/BeeGUTS#25]
Hi, it seems to me that the tutorial does not provide the right parameter estimates given the treatment numerical values. It seems for example that parameter z_w should be around 9, while your output gives 2.37407e-01.

**Comment by Carlor87** [comment]
Dear Sandrine,

Thank you for pointing this issue on the tutorial file out. The loading of the datafile done in the tutorial is incorrect and will be fixed in the next release (which should happen soon). Please refer to the README file of the github version for now.
The mismatch is originated by loading the datafile for teh Chronic Oral test without the additional argument cstConcCal = FALSE
The argument cstConcCal (which is TRUE) by default is needed to transform from a unit of dose in food into a units of ingeste dose per bee. Given that the data are already in the correct units (of ug/bee), the transformation needs to be disabled.

**Comment by Carlor87** [comment]
Fix tutorial file in vignette folder
